theme: jekyll-theme-minimal
title: "Instagram Data Download Viewer by Micha Birklbauer"
description: "Project Website for Instagram Data Download Viewer"
logo: https://raw.githubusercontent.com/t0xic-m/t0xic-m.github.io/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instagram_data_download_viewer/archive/master.zip
  tar_url: https://github.com/t0xic-m/instagram_data_download_viewer/archive/master.tar.gz
